-- Flexible per-section access: custom roles with view/edit checkboxes.
-- Run this once in the Supabase SQL Editor (Project → SQL Editor → New query).
-- Safe to re-run: uses IF NOT EXISTS / ON CONFLICT / DROP-then-CREATE for policies.

-- 1. New tables ---------------------------------------------------------

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.role_permissions (
  role_id bigint not null references public.roles(id) on delete cascade,
  section text not null,
  can_view boolean not null default false,
  can_edit boolean not null default false,
  primary key (role_id, section)
);

alter table public.user_roles add column if not exists role_id bigint references public.roles(id);

-- 2. Helper functions used by RLS policies -------------------------------

create or replace function public.is_admin()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.user_roles where user_id = auth.uid() and role = 'admin'
  );
$$;

create or replace function public.has_access(p_section text, p_need text)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select coalesce((
    select
      case
        when ur.role = 'admin' then true
        when p_need = 'edit' then rp.can_edit
        else rp.can_view
      end
    from public.user_roles ur
    left join public.role_permissions rp
      on rp.role_id = ur.role_id and rp.section = p_section
    where ur.user_id = auth.uid()
  ), false);
$$;

-- 3. Reset RLS policies on affected tables -------------------------------
-- (drops whatever existed before, regardless of name, then recreates cleanly)

do $$
declare pol record;
begin
  for pol in
    select policyname, tablename from pg_policies
    where schemaname = 'public'
      and tablename in ('traffic_entries', 'extra_expenses', 'month_status', 'user_roles', 'roles', 'role_permissions')
  loop
    execute format('drop policy if exists %I on public.%I', pol.policyname, pol.tablename);
  end loop;
end $$;

alter table public.traffic_entries enable row level security;
alter table public.extra_expenses enable row level security;
alter table public.month_status enable row level security;
alter table public.user_roles enable row level security;
alter table public.roles enable row level security;
alter table public.role_permissions enable row level security;

create policy traffic_entries_select on public.traffic_entries
  for select using (public.has_access('marketing.data_entry', 'view'));
create policy traffic_entries_insert on public.traffic_entries
  for insert with check (public.has_access('marketing.data_entry', 'edit'));
create policy traffic_entries_update on public.traffic_entries
  for update using (public.has_access('marketing.data_entry', 'edit'))
  with check (public.has_access('marketing.data_entry', 'edit'));

create policy extra_expenses_select on public.extra_expenses
  for select using (public.has_access('marketing.data_entry', 'view'));
create policy extra_expenses_insert on public.extra_expenses
  for insert with check (public.has_access('marketing.data_entry', 'edit'));
create policy extra_expenses_update on public.extra_expenses
  for update using (public.has_access('marketing.data_entry', 'edit'))
  with check (public.has_access('marketing.data_entry', 'edit'));

-- Closing/reopening a month stays admin-only regardless of section access.
create policy month_status_select on public.month_status
  for select using (public.has_access('marketing.data_entry', 'view'));
create policy month_status_insert on public.month_status
  for insert with check (public.is_admin());
create policy month_status_update on public.month_status
  for update using (public.is_admin()) with check (public.is_admin());

create policy user_roles_select_own on public.user_roles
  for select using (user_id = auth.uid());

create policy roles_select_authenticated on public.roles
  for select using (auth.role() = 'authenticated');
create policy role_permissions_select_authenticated on public.role_permissions
  for select using (auth.role() = 'authenticated');

-- 4. Preserve current behaviour for any existing non-admin accounts ------
-- (a default "Редактор" role with the same full access editors had before)

insert into public.roles (name) values ('Редактор') on conflict (name) do nothing;

insert into public.role_permissions (role_id, section, can_view, can_edit)
select r.id, s.section, true, true
from public.roles r
cross join (values
  ('marketing.statistics'),
  ('marketing.data_entry'),
  ('marketing.publications'),
  ('marketing.instagram_target')
) as s(section)
where r.name = 'Редактор'
on conflict (role_id, section) do nothing;

update public.user_roles ur
set role_id = r.id
from public.roles r
where r.name = 'Редактор' and ur.role = 'editor' and ur.role_id is null;
