-- Employee display names + city/store hierarchy with per-role store access.
-- Run this once in the Supabase SQL Editor. Safe to re-run.

alter table public.user_roles add column if not exists full_name text;

create table if not exists public.cities (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.stores (
  id bigint generated by default as identity primary key,
  city_id bigint not null references public.cities(id) on delete cascade,
  name text not null,
  code text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.role_store_access (
  id bigint generated by default as identity primary key,
  role_id bigint not null references public.roles(id) on delete cascade,
  scope text not null check (scope in ('all', 'city', 'store')),
  city_id bigint references public.cities(id) on delete cascade,
  store_id bigint references public.stores(id) on delete cascade
);

create unique index if not exists role_store_access_unique
  on public.role_store_access (role_id, scope, coalesce(city_id, -1), coalesce(store_id, -1));

create or replace function public.has_store_access(p_store_code text)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select coalesce((
    select
      case
        when ur.role = 'admin' then true
        else exists (
          select 1
          from public.role_store_access rsa
          join public.stores s on s.code = p_store_code
          where rsa.role_id = ur.role_id
            and (
              rsa.scope = 'all'
              or (rsa.scope = 'city' and rsa.city_id = s.city_id)
              or (rsa.scope = 'store' and rsa.store_id = s.id)
            )
        )
      end
    from public.user_roles ur
    where ur.user_id = auth.uid()
  ), false);
$$;

do $$
declare pol record;
begin
  for pol in
    select policyname, tablename from pg_policies
    where schemaname = 'public'
      and tablename in ('traffic_entries', 'month_status', 'cities', 'stores', 'role_store_access')
  loop
    execute format('drop policy if exists %I on public.%I', pol.policyname, pol.tablename);
  end loop;
end $$;

alter table public.cities enable row level security;
alter table public.stores enable row level security;
alter table public.role_store_access enable row level security;

create policy cities_select_authenticated on public.cities for select using (auth.role() = 'authenticated');
create policy stores_select_authenticated on public.stores for select using (auth.role() = 'authenticated');
create policy role_store_access_select_own on public.role_store_access for select using (
  exists (select 1 from public.user_roles ur where ur.user_id = auth.uid() and ur.role_id = role_store_access.role_id)
);

create policy traffic_entries_select on public.traffic_entries
  for select using (public.has_access('marketing.data_entry', 'view') and public.has_store_access(store));
create policy traffic_entries_insert on public.traffic_entries
  for insert with check (public.has_access('marketing.data_entry', 'edit') and public.has_store_access(store));
create policy traffic_entries_update on public.traffic_entries
  for update using (public.has_access('marketing.data_entry', 'edit') and public.has_store_access(store))
  with check (public.has_access('marketing.data_entry', 'edit') and public.has_store_access(store));

create policy month_status_select on public.month_status
  for select using (public.has_access('marketing.data_entry', 'view') and public.has_store_access(store));
create policy month_status_insert on public.month_status
  for insert with check (public.has_access('marketing.data_entry', 'edit') and public.has_store_access(store));
create policy month_status_update on public.month_status
  for update using (public.has_access('marketing.data_entry', 'edit') and public.has_store_access(store))
  with check (public.has_access('marketing.data_entry', 'edit') and public.has_store_access(store));

-- Seed one city with the two existing point codes so nothing already stored breaks;
-- rename/reorganize freely from Settings -> Города и точки afterwards.
insert into public.cities (name) values ('Город 1') on conflict (name) do nothing;

insert into public.stores (city_id, name, code)
select c.id, v.name, v.code
from public.cities c
cross join (values ('Точка 1', 'point_1'), ('Точка 2', 'point_2')) as v(name, code)
where c.name = 'Город 1'
on conflict (code) do nothing;

insert into public.role_store_access (role_id, scope)
select r.id, 'all'
from public.roles r
where r.name = 'Редактор'
on conflict (role_id, scope, coalesce(city_id, -1), coalesce(store_id, -1)) do nothing;
