-- Публикации: manual log of Instagram posts/reels per store, with engagement
-- metrics entered by hand (no live API integration). Run once in the
-- Supabase SQL Editor. Safe to re-run.

create table if not exists public.publication_entries (
  id bigint generated by default as identity primary key,
  store text not null,
  entry_date date not null,
  entry_time time,
  post_type text not null default 'post' check (post_type in ('post', 'reel')),
  source text not null default 'organic' check (source in ('organic', 'ads')),
  reach integer not null default 0,
  views integer not null default 0,
  likes integer not null default 0,
  comments integer not null default 0,
  shares integer not null default 0,
  caption text,
  created_at timestamptz not null default now()
);

create index if not exists publication_entries_date_idx on public.publication_entries (entry_date);
create index if not exists publication_entries_store_idx on public.publication_entries (store);

do $$
declare pol record;
begin
  for pol in
    select policyname, tablename from pg_policies
    where schemaname = 'public' and tablename = 'publication_entries'
  loop
    execute format('drop policy if exists %I on public.%I', pol.policyname, pol.tablename);
  end loop;
end $$;

alter table public.publication_entries enable row level security;

create policy publication_entries_select on public.publication_entries
  for select using (public.has_access('marketing.publications', 'view') and public.has_store_access(store));
create policy publication_entries_insert on public.publication_entries
  for insert with check (public.has_access('marketing.publications', 'edit') and public.has_store_access(store));
create policy publication_entries_update on public.publication_entries
  for update using (public.has_access('marketing.publications', 'edit') and public.has_store_access(store))
  with check (public.has_access('marketing.publications', 'edit') and public.has_store_access(store));
create policy publication_entries_delete on public.publication_entries
  for delete using (public.has_access('marketing.publications', 'edit') and public.has_store_access(store));
