-- Per-row lock on data-entry rows: once a day's traffic entry or an expense
-- row has been saved, it locks. Editing it again needs a one-time unlock,
-- granted by an admin approving a request from the new "Запросы" section.
-- Run once in the Supabase SQL Editor. Safe to re-run.

alter table public.traffic_entries add column if not exists locked boolean not null default false;
alter table public.extra_expenses add column if not exists locked boolean not null default false;

create table if not exists public.edit_requests (
  id bigint generated by default as identity primary key,
  table_name text not null check (table_name in ('traffic_entries', 'extra_expenses')),
  row_id bigint not null,
  store text,
  context text,
  requested_by uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'approved', 'denied')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

do $$
declare pol record;
begin
  for pol in
    select policyname, tablename from pg_policies
    where schemaname = 'public' and tablename in ('traffic_entries', 'extra_expenses', 'edit_requests')
  loop
    execute format('drop policy if exists %I on public.%I', pol.policyname, pol.tablename);
  end loop;
end $$;

alter table public.edit_requests enable row level security;

create policy traffic_entries_select on public.traffic_entries
  for select using (public.has_access('marketing.data_entry', 'view') and public.has_store_access(store));
create policy traffic_entries_insert on public.traffic_entries
  for insert with check (public.has_access('marketing.data_entry', 'edit') and public.has_store_access(store));
create policy traffic_entries_update on public.traffic_entries
  for update using (public.has_access('marketing.data_entry', 'edit') and public.has_store_access(store) and not locked)
  with check (public.has_access('marketing.data_entry', 'edit') and public.has_store_access(store));

create policy extra_expenses_select on public.extra_expenses
  for select using (public.has_access('marketing.data_entry', 'view'));
create policy extra_expenses_insert on public.extra_expenses
  for insert with check (public.has_access('marketing.data_entry', 'edit'));
create policy extra_expenses_update on public.extra_expenses
  for update using (public.has_access('marketing.data_entry', 'edit') and not locked)
  with check (public.has_access('marketing.data_entry', 'edit'));

create policy edit_requests_select on public.edit_requests
  for select using (requested_by = auth.uid() or public.is_admin());
create policy edit_requests_insert on public.edit_requests
  for insert with check (
    public.has_access('marketing.data_entry', 'edit')
    and (store is null or public.has_store_access(store))
    and requested_by = auth.uid()
  );
