-- 1. Deleting an employee must not wipe their request history — only sever
--    the auth.users link; the row (and the requester's name already baked
--    into its context text) stays. Previously this cascaded and deleted
--    the whole row.
do $$
declare fk record;
begin
  for fk in
    select conname from pg_constraint
    where conrelid = 'public.edit_requests'::regclass and contype = 'f'
  loop
    execute format('alter table public.edit_requests drop constraint %I', fk.conname);
  end loop;
end $$;

alter table public.edit_requests alter column requested_by drop not null;
alter table public.edit_requests add constraint edit_requests_requested_by_fkey
  foreign key (requested_by) references auth.users(id) on delete set null;

-- 2. A log of "secondary" edits — changes to a row that had already been
--    saved once before (i.e. made after an approved unlock request). The
--    employee's name is captured at write time (changed_by_name) so it
--    keeps showing correctly even after that employee is deleted.
create table if not exists public.edit_history (
  id bigint generated by default as identity primary key,
  table_name text not null check (table_name in ('traffic_entries', 'extra_expenses')),
  row_id bigint not null,
  store text,
  summary text not null,
  changed_by uuid references auth.users(id) on delete set null,
  changed_by_name text not null,
  created_at timestamptz not null default now()
);

alter table public.edit_history enable row level security;

drop policy if exists edit_history_select on public.edit_history;
create policy edit_history_select on public.edit_history
  for select using (public.has_access('history', 'view'));

drop policy if exists edit_history_insert on public.edit_history;
create policy edit_history_insert on public.edit_history
  for insert with check (public.has_access('marketing.data_entry', 'edit'));
