-- Presence: a heartbeat row per user, refreshed periodically while the app
-- is open. "Online" is inferred client-side from how fresh last_seen_at is
-- — there's no separate "went offline" event, it's just staleness.
create table if not exists public.user_presence (
  user_id uuid primary key references auth.users(id) on delete cascade,
  last_seen_at timestamptz not null default now()
);

alter table public.user_presence enable row level security;

drop policy if exists user_presence_insert on public.user_presence;
create policy user_presence_insert on public.user_presence
  for insert with check (user_id = auth.uid());
drop policy if exists user_presence_update on public.user_presence;
create policy user_presence_update on public.user_presence
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists user_presence_select on public.user_presence;
create policy user_presence_select on public.user_presence
  for select using (public.has_access('settings.employees', 'view'));

-- Login history: one row per actual sign-in (not every page reload), with
-- the device captured from the browser's user agent string.
create table if not exists public.user_login_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  user_name text not null,
  user_agent text,
  logged_in_at timestamptz not null default now()
);

alter table public.user_login_events enable row level security;

drop policy if exists user_login_events_insert on public.user_login_events;
create policy user_login_events_insert on public.user_login_events
  for insert with check (user_id = auth.uid());
drop policy if exists user_login_events_select on public.user_login_events;
create policy user_login_events_select on public.user_login_events
  for select using (public.has_access('settings.employees', 'view'));
