-- МойСклад integration, stage 1: sales/revenue by register (касса), not
-- just by city — a city can have several registers (e.g. "Overman Актобе"
-- and "Актобе скидка") that need to show up as separate rows but also roll
-- up into that city's totals. Data is pulled by a daily sync job
-- (server-side, service role) and stored here — the portal only ever reads
-- from these tables, nobody hits the МойСклад API on page load.

create table if not exists public.moysklad_registers (
  id text primary key, -- МойСклад entity id
  name text not null, -- e.g. "Overman Актобе", "Актобе скидка"
  store text references public.stores(code) on delete set null, -- which of our stores this rolls up into; null until mapped
  created_at timestamptz not null default now()
);

create table if not exists public.moysklad_sales_daily (
  id bigint generated by default as identity primary key,
  register_id text not null references public.moysklad_registers(id) on delete cascade,
  sale_date date not null,
  revenue numeric not null default 0,
  receipts_count integer not null default 0,
  items_count numeric not null default 0, -- sum of line-item quantities, for "вещей в чеке"
  cost numeric, -- себестоимость проданного, for margin %; null if unknown
  synced_at timestamptz not null default now(),
  unique (register_id, sale_date)
);

create table if not exists public.moysklad_sync_state (
  id boolean primary key default true check (id),
  last_synced_at timestamptz,
  last_status text,
  last_error text
);
insert into public.moysklad_sync_state (id) values (true) on conflict (id) do nothing;

do $$
declare pol record;
begin
  for pol in
    select policyname, tablename from pg_policies
    where schemaname = 'public'
      and tablename in ('moysklad_registers', 'moysklad_sales_daily', 'moysklad_sync_state')
  loop
    execute format('drop policy if exists %I on public.%I', pol.policyname, pol.tablename);
  end loop;
end $$;

alter table public.moysklad_registers enable row level security;
alter table public.moysklad_sales_daily enable row level security;
alter table public.moysklad_sync_state enable row level security;

create policy moysklad_registers_select on public.moysklad_registers
  for select using (public.has_access('marketing.statistics', 'view'));
create policy moysklad_sales_daily_select on public.moysklad_sales_daily
  for select using (public.has_access('marketing.statistics', 'view'));
create policy moysklad_sync_state_select on public.moysklad_sync_state
  for select using (public.is_admin());
