-- Аналитика конкурентов, stage 1: just the tracked-account list. Company-wide,
-- not per-store — competitor content isn't tied to a single point of sale.
-- No live data yet (that needs an Apify token); this just lets the list be
-- filled in ahead of time.

create table if not exists public.tracked_competitors (
  id bigint generated by default as identity primary key,
  platform text not null check (platform in ('instagram', 'tiktok')),
  handle text not null, -- @username, without the @
  display_name text,
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_by_name text,
  created_at timestamptz not null default now(),
  unique (platform, handle)
);

do $$
declare pol record;
begin
  for pol in
    select policyname, tablename from pg_policies
    where schemaname = 'public' and tablename = 'tracked_competitors'
  loop
    execute format('drop policy if exists %I on public.%I', pol.policyname, pol.tablename);
  end loop;
end $$;

alter table public.tracked_competitors enable row level security;

create policy tracked_competitors_select on public.tracked_competitors
  for select using (public.has_access('marketing.competitor_analytics', 'view'));
create policy tracked_competitors_insert on public.tracked_competitors
  for insert with check (public.has_access('marketing.competitor_analytics', 'edit'));
create policy tracked_competitors_delete on public.tracked_competitors
  for delete using (public.has_access('marketing.competitor_analytics', 'edit'));
