-- Аналитика конкурентов, stage 2: the actual posts/Reels table that "Топ
-- контента" ranks by engagement. Empty until the Apify sync is wired up —
-- this just gives the period filter something real to query.

create table if not exists public.competitor_content (
  id bigint generated by default as identity primary key,
  competitor_id bigint not null references public.tracked_competitors(id) on delete cascade,
  platform text not null check (platform in ('instagram', 'tiktok')),
  post_url text not null,
  posted_at timestamptz not null,
  caption text,
  media_type text, -- 'reel', 'post', 'video', ...
  thumbnail_url text,
  likes integer not null default 0,
  comments integer not null default 0,
  shares integer not null default 0,
  views integer not null default 0,
  synced_at timestamptz not null default now(),
  unique (platform, post_url)
);

create index if not exists competitor_content_posted_at_idx on public.competitor_content (posted_at);

do $$
declare pol record;
begin
  for pol in
    select policyname, tablename from pg_policies
    where schemaname = 'public' and tablename = 'competitor_content'
  loop
    execute format('drop policy if exists %I on public.%I', pol.policyname, pol.tablename);
  end loop;
end $$;

alter table public.competitor_content enable row level security;

-- Read-only for staff — rows only ever get written server-side by the (future)
-- sync job using the service role, same pattern as moysklad_sales_daily.
create policy competitor_content_select on public.competitor_content
  for select using (public.has_access('marketing.competitor_analytics', 'view'));
