-- Настройки → Пароли: manually-entered login/password credentials for
-- external accounts (social networks etc.), grouped by network. No
-- request/approval flow — anyone granted "view" on settings.passwords can
-- see and reveal every row; the owner controls who gets that via Права/Роли,
-- same as any other section.

create table if not exists public.stored_passwords (
  id bigint generated by default as identity primary key,
  social_network text not null,
  login text not null,
  password text not null,
  label text, -- optional free-text note, e.g. "основной аккаунт"
  created_by uuid references auth.users(id) on delete set null,
  created_by_name text,
  created_at timestamptz not null default now()
);

alter table public.stored_passwords enable row level security;

do $$
declare pol record;
begin
  for pol in
    select policyname, tablename from pg_policies
    where schemaname = 'public' and tablename = 'stored_passwords'
  loop
    execute format('drop policy if exists %I on public.%I', pol.policyname, pol.tablename);
  end loop;
end $$;

create policy stored_passwords_select on public.stored_passwords
  for select using (public.has_access('settings.passwords', 'view'));
create policy stored_passwords_insert on public.stored_passwords
  for insert with check (public.has_access('settings.passwords', 'edit'));
create policy stored_passwords_update on public.stored_passwords
  for update using (public.has_access('settings.passwords', 'edit'))
  with check (public.has_access('settings.passwords', 'edit'));
create policy stored_passwords_delete on public.stored_passwords
  for delete using (public.has_access('settings.passwords', 'edit'));
