-- Turns "соцсеть" from free text into a managed list (so grouping is exact,
-- never a case/spelling mismatch), and adds an append-only history log of
-- login/password changes per account — shown per social network.

create table if not exists public.social_networks (
  id bigint generated by default as identity primary key,
  name text not null,
  created_by uuid references auth.users(id) on delete set null,
  created_by_name text,
  created_at timestamptz not null default now()
);
-- Case-insensitive uniqueness: "Instagram" and "instagram" are the same network.
create unique index if not exists social_networks_name_lower_idx on public.social_networks (lower(name));

alter table public.stored_passwords
  add column if not exists social_network_id bigint references public.social_networks(id) on delete restrict;

-- Backfill any existing free-text rows into the new managed list (prod has
-- none right now, but this keeps the migration safe to run at any point).
insert into public.social_networks (name)
select distinct trim(social_network) from public.stored_passwords
where trim(coalesce(social_network, '')) <> ''
on conflict (lower(name)) do nothing;

update public.stored_passwords sp
set social_network_id = sn.id
from public.social_networks sn
where sp.social_network_id is null and lower(sn.name) = lower(trim(sp.social_network));

alter table public.stored_passwords alter column social_network_id set not null;
alter table public.stored_passwords drop column if exists social_network;

create table if not exists public.stored_password_history (
  id bigint generated by default as identity primary key,
  password_id bigint not null references public.stored_passwords(id) on delete cascade,
  old_login text not null,
  old_password text not null,
  changed_by_name text,
  changed_at timestamptz not null default now()
);

alter table public.social_networks enable row level security;
alter table public.stored_password_history enable row level security;

do $$
declare pol record;
begin
  for pol in
    select policyname, tablename from pg_policies
    where schemaname = 'public' and tablename in ('social_networks', 'stored_password_history')
  loop
    execute format('drop policy if exists %I on public.%I', pol.policyname, pol.tablename);
  end loop;
end $$;

create policy social_networks_select on public.social_networks
  for select using (public.has_access('settings.passwords', 'view'));
create policy social_networks_insert on public.social_networks
  for insert with check (public.has_access('settings.passwords', 'edit'));
create policy social_networks_delete on public.social_networks
  for delete using (public.has_access('settings.passwords', 'edit'));

create policy stored_password_history_select on public.stored_password_history
  for select using (public.has_access('settings.passwords', 'view'));
create policy stored_password_history_insert on public.stored_password_history
  for insert with check (public.has_access('settings.passwords', 'edit'));
