-- Per-employee sales, alongside the existing per-register table. МойСклад
-- tags every retaildemand/retailsalesreturn with an "owner" (ответственный)
-- — confirmed live against the account that this is the real cashier who
-- rang up the sale, not a generic API user. Same RLS as
-- moysklad_sales_daily (marketing.statistics view) — store filtering
-- happens client-side against the sidebar's city selector, same pattern.

create table if not exists public.moysklad_employee_sales_daily (
  id bigint generated by default as identity primary key,
  employee_ms_id text not null, -- МойСклад entity/employee id
  employee_name text not null, -- snapshot at sync time; a name change later doesn't rewrite history
  sale_date date not null,
  store text references public.stores(code) on delete set null,
  revenue numeric not null default 0,
  receipts_count integer not null default 0,
  items_count numeric not null default 0,
  cost numeric,
  returned_amount numeric not null default 0,
  returned_receipts integer not null default 0,
  returned_items numeric not null default 0,
  synced_at timestamptz not null default now(),
  unique (employee_ms_id, sale_date, store)
);

alter table public.moysklad_employee_sales_daily enable row level security;

do $$
declare pol record;
begin
  for pol in
    select policyname, tablename from pg_policies
    where schemaname = 'public' and tablename = 'moysklad_employee_sales_daily'
  loop
    execute format('drop policy if exists %I on public.%I', pol.policyname, pol.tablename);
  end loop;
end $$;

create policy moysklad_employee_sales_daily_select on public.moysklad_employee_sales_daily
  for select using (public.has_access('marketing.statistics', 'view'));
