-- Product-level МойСклад data for the "Склад" section: catalog (name +
-- category), a live stock snapshot (for "Зависшие остатки"), and daily
-- per-product sales (for АВС/XYZ анализ). All three are read-only from the
-- portal's side — populated by the same sync job as the register/employee
-- tables, just extended.

create table if not exists public.moysklad_products (
  id text primary key, -- МойСклад entity/product id
  name text not null,
  category text, -- productFolder.name; null if uncategorized
  buy_price numeric, -- себестоимость, in tenge (kopecks / 100)
  archived boolean not null default false,
  synced_at timestamptz not null default now()
);

create table if not exists public.moysklad_product_stock (
  product_ms_id text primary key references public.moysklad_products(id) on delete cascade,
  product_name text not null, -- snapshot, so a stale row still displays fine
  category text,
  stock numeric not null default 0,
  buy_price numeric, -- for "Деньги" (stock × buy_price)
  stock_days numeric, -- МойСклад's own "оборачиваемость, дней" — days current stock has been sitting
  synced_at timestamptz not null default now()
);

create table if not exists public.moysklad_product_sales_daily (
  id bigint generated by default as identity primary key,
  product_ms_id text not null references public.moysklad_products(id) on delete cascade,
  product_name text not null, -- snapshot at sync time
  sale_date date not null,
  revenue numeric not null default 0,
  quantity numeric not null default 0,
  cost numeric not null default 0,
  returned_amount numeric not null default 0,
  returned_quantity numeric not null default 0,
  synced_at timestamptz not null default now(),
  unique (product_ms_id, sale_date)
);

create index if not exists moysklad_product_sales_daily_date_idx
  on public.moysklad_product_sales_daily (sale_date);

alter table public.moysklad_products enable row level security;
alter table public.moysklad_product_stock enable row level security;
alter table public.moysklad_product_sales_daily enable row level security;

do $$
declare pol record;
begin
  for pol in
    select policyname, tablename from pg_policies
    where schemaname = 'public'
      and tablename in ('moysklad_products', 'moysklad_product_stock', 'moysklad_product_sales_daily')
  loop
    execute format('drop policy if exists %I on public.%I', pol.policyname, pol.tablename);
  end loop;
end $$;

create policy moysklad_products_select on public.moysklad_products
  for select using (public.has_access('warehouse.stock', 'view'));
create policy moysklad_product_stock_select on public.moysklad_product_stock
  for select using (public.has_access('warehouse.stock', 'view'));
create policy moysklad_product_sales_daily_select on public.moysklad_product_sales_daily
  for select using (public.has_access('warehouse.stock', 'view'));

-- Pre-aggregated per-product totals for a date range — the АВС/XYZ page
-- needs revenue/quantity/cost summed and a distinct-days-with-sales count
-- per product, and doing that client-side would mean pulling every daily
-- row for every product over the whole analysis window (tens of thousands
-- of rows, well past PostgREST's default row cap). Runs with the caller's
-- own privileges, so the two tables' own RLS (has_access above) still
-- applies exactly as if the caller had queried them directly.
create or replace function public.product_sales_summary(p_from date, p_to date)
returns table (
  product_ms_id text,
  product_name text,
  category text,
  revenue numeric,
  quantity numeric,
  cost numeric,
  days_with_sales integer
)
language sql
stable
as $$
  select
    s.product_ms_id,
    coalesce(p.name, max(s.product_name)) as product_name,
    p.category,
    sum(s.revenue) as revenue,
    sum(s.quantity) as quantity,
    sum(s.cost) as cost,
    count(*) filter (where s.quantity > 0)::int as days_with_sales
  from public.moysklad_product_sales_daily s
  left join public.moysklad_products p on p.id = s.product_ms_id
  where s.sale_date between p_from and p_to
  group by s.product_ms_id, p.name, p.category
$$;
