-- План продаж по продавцам на месяц: одна строка = точка + сотрудник (из
-- МойСклад) + месяц, план — одним числом на весь месяц. План точки и месяца в
-- окне «План продаж» на «Обзоре» и «Продаже» — сумма планов продавцов.
-- Вносится кнопкой «Внесение плана продаж по сотрудникам» на странице «Продажа».
-- Правила как у плана трафика (см. 053_traffic_plan_lock.sql): внести план на
-- месяц можно свободно один раз, изменить уже внесённый — только по одобренному
-- запросу (30-минутное окно unlock_expires_at, его открывает
-- app/api/edit-requests/[id]/approve).
-- Доступ: внесение — раздел «sales.plan» (право edit), чтение — те, кто видит
-- «Продажу» (marketing.statistics) или имеет sales.plan.

-- Убираем таблицу плана по датам — от неё отказались до боевого использования.
drop table if exists public.sales_plan_entries cascade;
drop function if exists public.sales_plan_entries_protect_plan();

create table if not exists public.sales_plan_monthly (
  id bigint generated by default as identity primary key,
  store text not null references public.stores(code),
  employee_ms_id text not null,
  employee_name text not null,
  plan_month date not null, -- первое число месяца
  sales_plan numeric,
  locked boolean not null default false,
  unlock_expires_at timestamptz,
  created_at timestamptz not null default now(),
  unique (store, employee_ms_id, plan_month)
);

alter table public.sales_plan_monthly enable row level security;

drop policy if exists sales_plan_monthly_select on public.sales_plan_monthly;
create policy sales_plan_monthly_select on public.sales_plan_monthly
  for select using (
    (public.has_access('marketing.statistics', 'view') or public.has_access('sales.plan', 'view'))
    and public.has_store_access(store)
  );

drop policy if exists sales_plan_monthly_insert on public.sales_plan_monthly;
create policy sales_plan_monthly_insert on public.sales_plan_monthly
  for insert with check (
    public.has_access('sales.plan', 'edit')
    and public.has_store_access(store)
  );

drop policy if exists sales_plan_monthly_update on public.sales_plan_monthly;
create policy sales_plan_monthly_update on public.sales_plan_monthly
  for update using (
    public.has_access('sales.plan', 'edit')
    and public.has_store_access(store)
  )
  with check (
    public.has_access('sales.plan', 'edit')
    and public.has_store_access(store)
  );

-- Политики строк не умеют сравнивать старое и новое значение, поэтому защиту
-- «план уже внесён — менять только по запросу» держит триггер.
create or replace function public.sales_plan_monthly_protect_plan()
returns trigger
language plpgsql
as $$
begin
  if old.sales_plan is not null
     and new.sales_plan is distinct from old.sales_plan
     and (old.unlock_expires_at is null or old.unlock_expires_at <= now())
  then
    raise exception 'план продаж уже внесён — нужен одобренный запрос на изменение';
  end if;
  return new;
end;
$$;

drop trigger if exists sales_plan_monthly_protect_plan_trigger on public.sales_plan_monthly;
create trigger sales_plan_monthly_protect_plan_trigger
  before update on public.sales_plan_monthly
  for each row
  execute function public.sales_plan_monthly_protect_plan();

-- Запросы на изменение и история изменений знают про новую таблицу, а вносить
-- запрос/запись истории может и тот, у кого есть право на план продаж.
alter table public.edit_requests drop constraint if exists edit_requests_table_name_check;
alter table public.edit_requests add constraint edit_requests_table_name_check
  check (table_name in ('traffic_entries', 'extra_expenses', 'sales_plan_monthly'));

alter table public.edit_history drop constraint if exists edit_history_table_name_check;
alter table public.edit_history add constraint edit_history_table_name_check
  check (table_name in ('traffic_entries', 'extra_expenses', 'sales_plan_monthly'));

drop policy if exists edit_requests_insert on public.edit_requests;
create policy edit_requests_insert on public.edit_requests
  for insert with check (
    (public.has_access('marketing.data_entry', 'edit') or public.has_access('sales.plan', 'edit'))
    and (store is null or public.has_store_access(store))
    and requested_by = auth.uid()
  );

drop policy if exists edit_history_insert on public.edit_history;
create policy edit_history_insert on public.edit_history
  for insert with check (
    public.has_access('marketing.data_entry', 'edit') or public.has_access('sales.plan', 'edit')
  );
