-- План продаж по датам и точкам. Вносится на странице «Продажа», показывается
-- окном «План продаж» на «Обзоре» и «Продаже».
-- Правила — как у плана трафика (см. 053_traffic_plan_lock.sql): внести план на
-- дату можно свободно один раз (любая дата, в том числе вперёд), а изменить уже
-- внесённый — только по одобренному запросу (30-минутное окно unlock_expires_at,
-- его открывает app/api/edit-requests/[id]/approve).
-- Доступ: внесение — раздел «sales.plan» (право edit), чтение — те, кто видит
-- «Продажу» (marketing.statistics) или имеет sales.plan.

create table if not exists public.sales_plan_entries (
  id bigint generated by default as identity primary key,
  store text not null references public.stores(code),
  entry_date date not null,
  sales_plan numeric,
  locked boolean not null default false,
  unlock_expires_at timestamptz,
  created_at timestamptz not null default now(),
  unique (store, entry_date)
);

alter table public.sales_plan_entries enable row level security;

drop policy if exists sales_plan_entries_select on public.sales_plan_entries;
create policy sales_plan_entries_select on public.sales_plan_entries
  for select using (
    (public.has_access('marketing.statistics', 'view') or public.has_access('sales.plan', 'view'))
    and public.has_store_access(store)
  );

drop policy if exists sales_plan_entries_insert on public.sales_plan_entries;
create policy sales_plan_entries_insert on public.sales_plan_entries
  for insert with check (
    public.has_access('sales.plan', 'edit')
    and public.has_store_access(store)
  );

drop policy if exists sales_plan_entries_update on public.sales_plan_entries;
create policy sales_plan_entries_update on public.sales_plan_entries
  for update using (
    public.has_access('sales.plan', 'edit')
    and public.has_store_access(store)
  )
  with check (
    public.has_access('sales.plan', 'edit')
    and public.has_store_access(store)
  );

-- Политики строк не умеют сравнивать старое и новое значение, поэтому защиту
-- «план уже внесён — менять только по запросу» держит триггер.
create or replace function public.sales_plan_entries_protect_plan()
returns trigger
language plpgsql
as $$
begin
  if old.sales_plan is not null
     and new.sales_plan is distinct from old.sales_plan
     and (old.unlock_expires_at is null or old.unlock_expires_at <= now())
  then
    raise exception 'план продаж уже внесён — нужен одобренный запрос на изменение';
  end if;
  return new;
end;
$$;

drop trigger if exists sales_plan_entries_protect_plan_trigger on public.sales_plan_entries;
create trigger sales_plan_entries_protect_plan_trigger
  before update on public.sales_plan_entries
  for each row
  execute function public.sales_plan_entries_protect_plan();

-- Запросы на изменение и история изменений знают про новую таблицу, а вносить
-- запрос/запись истории может и тот, у кого есть право на план продаж.
alter table public.edit_requests drop constraint if exists edit_requests_table_name_check;
alter table public.edit_requests add constraint edit_requests_table_name_check
  check (table_name in ('traffic_entries', 'extra_expenses', 'sales_plan_entries'));

alter table public.edit_history drop constraint if exists edit_history_table_name_check;
alter table public.edit_history add constraint edit_history_table_name_check
  check (table_name in ('traffic_entries', 'extra_expenses', 'sales_plan_entries'));

drop policy if exists edit_requests_insert on public.edit_requests;
create policy edit_requests_insert on public.edit_requests
  for insert with check (
    (public.has_access('marketing.data_entry', 'edit') or public.has_access('sales.plan', 'edit'))
    and (store is null or public.has_store_access(store))
    and requested_by = auth.uid()
  );

drop policy if exists edit_history_insert on public.edit_history;
create policy edit_history_insert on public.edit_history
  for insert with check (
    public.has_access('marketing.data_entry', 'edit') or public.has_access('sales.plan', 'edit')
  );
