-- Два периода месяца для плана продаж: на каждый — даты «с — по» и процент от
-- месячного плана точки, который на него приходится (например 1–15 числа — 40%,
-- 16–31 — 60%). Задаются на точку и месяц, общие для всех продавцов. Окно «План
-- продаж» по ним показывает план, факт и «нужно в день» текущего периода.
-- Правила как у плана продавцов (056_sales_plan_monthly.sql): внести свободно
-- один раз, изменить уже внесённое — только по одобренному запросу.

create table if not exists public.sales_plan_periods (
  id bigint generated by default as identity primary key,
  store text not null references public.stores(code),
  plan_month date not null, -- первое число месяца
  p1_from date,
  p1_to date,
  p1_percent numeric,
  p2_from date,
  p2_to date,
  p2_percent numeric,
  locked boolean not null default false,
  unlock_expires_at timestamptz,
  created_at timestamptz not null default now(),
  unique (store, plan_month)
);

alter table public.sales_plan_periods enable row level security;

drop policy if exists sales_plan_periods_select on public.sales_plan_periods;
create policy sales_plan_periods_select on public.sales_plan_periods
  for select using (
    (public.has_access('marketing.statistics', 'view') or public.has_access('sales.plan', 'view'))
    and public.has_store_access(store)
  );

drop policy if exists sales_plan_periods_insert on public.sales_plan_periods;
create policy sales_plan_periods_insert on public.sales_plan_periods
  for insert with check (
    public.has_access('sales.plan', 'edit')
    and public.has_store_access(store)
  );

drop policy if exists sales_plan_periods_update on public.sales_plan_periods;
create policy sales_plan_periods_update on public.sales_plan_periods
  for update using (
    public.has_access('sales.plan', 'edit')
    and public.has_store_access(store)
  )
  with check (
    public.has_access('sales.plan', 'edit')
    and public.has_store_access(store)
  );

-- Изменить уже внесённые периоды или проценты можно только в окне после
-- одобренного запроса; политики строк не сравнивают старое и новое, поэтому
-- это делает триггер.
create or replace function public.sales_plan_periods_protect()
returns trigger
language plpgsql
as $$
begin
  if (old.p1_from is not null or old.p1_to is not null or old.p1_percent is not null
      or old.p2_from is not null or old.p2_to is not null or old.p2_percent is not null)
     and (new.p1_from is distinct from old.p1_from or new.p1_to is distinct from old.p1_to
          or new.p1_percent is distinct from old.p1_percent
          or new.p2_from is distinct from old.p2_from or new.p2_to is distinct from old.p2_to
          or new.p2_percent is distinct from old.p2_percent)
     and (old.unlock_expires_at is null or old.unlock_expires_at <= now())
  then
    raise exception 'периоды плана продаж уже внесены — нужен одобренный запрос на изменение';
  end if;
  return new;
end;
$$;

drop trigger if exists sales_plan_periods_protect_trigger on public.sales_plan_periods;
create trigger sales_plan_periods_protect_trigger
  before update on public.sales_plan_periods
  for each row
  execute function public.sales_plan_periods_protect();

-- Запросы и история знают про новую таблицу.
alter table public.edit_requests drop constraint if exists edit_requests_table_name_check;
alter table public.edit_requests add constraint edit_requests_table_name_check
  check (table_name in ('traffic_entries', 'extra_expenses', 'sales_plan_monthly', 'sales_plan_periods'));

alter table public.edit_history drop constraint if exists edit_history_table_name_check;
alter table public.edit_history add constraint edit_history_table_name_check
  check (table_name in ('traffic_entries', 'extra_expenses', 'sales_plan_monthly', 'sales_plan_periods'));
