-- Бот-помощник для продавцов (Telegram): план/факт по каждому, что повысить,
-- цель на неделю. Один бот на всех; каждый продавец привязывается к своей
-- записи сотрудника МойСклад и работает только после подтверждения владельцем
-- на странице «Настройки → Помощник консультантов». Подтверждённого можно
-- отключить — бот перестаёт с ним работать.
--
-- Таблицы пишет только сервер (service role — вебхук бота и API портала),
-- страница портала читает coach_users по политике select.

create table if not exists public.coach_users (
  id bigint generated by default as identity primary key,
  telegram_user_id bigint not null unique,
  telegram_chat_id bigint not null,
  telegram_username text,
  telegram_name text,
  store text not null references public.stores(code),
  employee_ms_id text not null,
  employee_name text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'disabled')),
  requested_at timestamptz not null default now(),
  decided_at timestamptz,
  decided_by text,
  created_at timestamptz not null default now()
);

-- Один сотрудник МойСклад — один действующий Telegram-аккаунт (ожидающий или
-- подтверждённый): чужой аккаунт не может занять место человека.
create unique index if not exists coach_users_employee_active
  on public.coach_users (employee_ms_id)
  where status in ('pending', 'approved');

alter table public.coach_users enable row level security;

drop policy if exists coach_users_select on public.coach_users;
create policy coach_users_select on public.coach_users
  for select using (public.has_access('settings.coach', 'view'));

-- Журнал отправленных сообщений: чтобы повторный запуск расписания не слал
-- одно и то же дважды (одна запись на пользователя, вид и дату).
create table if not exists public.coach_messages_sent (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.coach_users(id) on delete cascade,
  kind text not null,
  ref_date date not null,
  sent_at timestamptz not null default now(),
  unique (user_id, kind, ref_date)
);

alter table public.coach_messages_sent enable row level security;
