-- Удержание отчётов (решение владельца 2026-10-05): если ночная сверка нашла расхождение и
-- автоисправление не помогло, неправильный отчёт в группы НЕ отправляется — он ждёт, пока
-- расхождение не исправят (или владелец сам не разрешит отправить как есть).
--
-- report_holds — расхождения, которые не удалось исправить: за какой день и по какому городу
-- (store = point_1 / point_3 / all). Пока статус 'held', отчёты этого города, в период
-- которых входит этот день, не отправляются.
-- held_reports — какие отчёты (дневной / недельный / месячный за такую-то дату) из-за этого
-- не ушли, чтобы отправить их сразу после исправления.
-- Таблицы пишет и читает только сервер (service role).

create table if not exists public.report_holds (
  id bigint generated by default as identity primary key,
  check_date date not null,
  store text not null check (store in ('point_1', 'point_3', 'all')),
  status text not null default 'held' check (status in ('held', 'released')),
  reason text,
  created_at timestamptz not null default now(),
  released_at timestamptz,
  released_by text,
  unique (check_date, store)
);

create table if not exists public.held_reports (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('day', 'week', 'month')),
  report_date date not null,
  store text not null,
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  unique (kind, report_date, store)
);

alter table public.report_holds enable row level security;
alter table public.held_reports enable row level security;
