-- Раздел «Финансы»: счета, статьи (дерево «пункт → подпункт»), партнёры, поставщики,
-- операции (основа ДДС), долги (между магазинами / магазин ↔ поставщик /
-- партнёр ↔ магазин), плановые платежи, план ОПИУ и настройки.
-- Выручка и себестоимость в ОПИУ берутся из МойСклад автоматически
-- (moysklad_sales_daily), поэтому в операции их вносить не нужно.
-- Доступ: раздел finance.* — просмотр / внесение (admin и owner видят всё).

-- ── Счета ────────────────────────────────────────────────────────────────
create table if not exists public.fin_accounts (
  id bigint generated by default as identity primary key,
  name text not null,
  kind text not null default 'cash' check (kind in ('cash', 'bank', 'card', 'other')),
  store text references public.stores(code), -- null = общий счёт компании
  opening_balance numeric not null default 0,
  opening_date date not null default current_date,
  active boolean not null default true,
  sort integer not null default 0,
  created_at timestamptz not null default now()
);

-- ── Статьи: пункт (parent_id is null) → подпункт ─────────────────────────
-- opiu_group: куда статья попадает в ОПИУ; null — не входит в ОПИУ (движение
-- капитала: займы, взносы и выплаты партнёрам, переносы).
create table if not exists public.fin_categories (
  id bigint generated by default as identity primary key,
  parent_id bigint references public.fin_categories(id) on delete restrict,
  name text not null,
  kind text not null check (kind in ('income', 'expense')),
  opiu_group text check (opiu_group in ('revenue', 'cogs', 'opex', 'other_income', 'other_expense', 'tax')),
  active boolean not null default true,
  sort integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.fin_partners (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  note text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.fin_suppliers (
  id bigint generated by default as identity primary key,
  name text not null,
  bin text,
  phone text,
  payment_terms_days integer, -- отсрочка платежа по договору
  note text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- ── Операции (ДДС) ───────────────────────────────────────────────────────
-- kind: income — приход, expense — расход, transfer — перевод между счетами
-- (в ДДС не считается ни доходом, ни расходом, меняет только остатки счетов).
create table if not exists public.fin_operations (
  id bigint generated by default as identity primary key,
  op_date date not null,
  kind text not null check (kind in ('income', 'expense', 'transfer')),
  amount numeric not null check (amount > 0),
  account_id bigint not null references public.fin_accounts(id),
  to_account_id bigint references public.fin_accounts(id), -- только для transfer
  category_id bigint references public.fin_categories(id),
  store text references public.stores(code),
  supplier_id bigint references public.fin_suppliers(id),
  partner_id bigint references public.fin_partners(id),
  debt_id bigint, -- ссылка на fin_debts (если операция — погашение долга)
  comment text,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now()
);
create index if not exists fin_operations_date_idx on public.fin_operations (op_date);
create index if not exists fin_operations_account_idx on public.fin_operations (account_id);

-- ── Долги ────────────────────────────────────────────────────────────────
-- kind: store_store — между магазинами, supplier — магазин ↔ поставщик,
-- partner — партнёр ↔ магазин. direction: payable — магазин (store) должен,
-- receivable — должны магазину. Для store_store store = кто должен
-- (payable) / кому должны (receivable), counterparty_store — вторая сторона.
create table if not exists public.fin_debts (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('store_store', 'supplier', 'partner')),
  direction text not null default 'payable' check (direction in ('payable', 'receivable')),
  store text not null references public.stores(code),
  counterparty_store text references public.stores(code),
  supplier_id bigint references public.fin_suppliers(id),
  partner_id bigint references public.fin_partners(id),
  amount numeric not null check (amount > 0),
  debt_date date not null default current_date,
  due_date date,
  comment text,
  closed boolean not null default false,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now()
);

create table if not exists public.fin_debt_payments (
  id bigint generated by default as identity primary key,
  debt_id bigint not null references public.fin_debts(id) on delete cascade,
  pay_date date not null,
  amount numeric not null check (amount > 0),
  operation_id bigint references public.fin_operations(id) on delete set null,
  comment text,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now()
);
create index if not exists fin_debt_payments_debt_idx on public.fin_debt_payments (debt_id);

-- ── Плановые платежи ─────────────────────────────────────────────────────
create table if not exists public.fin_planned_payments (
  id bigint generated by default as identity primary key,
  due_date date not null,
  kind text not null default 'expense' check (kind in ('income', 'expense')),
  amount numeric not null check (amount > 0),
  category_id bigint references public.fin_categories(id),
  store text references public.stores(code),
  supplier_id bigint references public.fin_suppliers(id),
  partner_id bigint references public.fin_partners(id),
  account_id bigint references public.fin_accounts(id),
  repeat text not null default 'none' check (repeat in ('none', 'weekly', 'monthly')),
  status text not null default 'planned' check (status in ('planned', 'paid', 'cancelled')),
  operation_id bigint references public.fin_operations(id) on delete set null,
  comment text,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now()
);
create index if not exists fin_planned_due_idx on public.fin_planned_payments (due_date);

-- ── План ОПИУ: месяц × статья × магазин (null = вся компания) ─────────────
create table if not exists public.fin_pnl_plan (
  id bigint generated by default as identity primary key,
  plan_month date not null, -- первое число месяца
  category_id bigint not null references public.fin_categories(id) on delete cascade,
  store text references public.stores(code),
  amount numeric not null default 0,
  created_at timestamptz not null default now()
);
create unique index if not exists fin_pnl_plan_unique
  on public.fin_pnl_plan (plan_month, category_id, coalesce(store, ''));

-- ── Настройки («Условия») ────────────────────────────────────────────────
create table if not exists public.fin_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);
insert into public.fin_settings (key, value) values
  ('auto_revenue', 'true'::jsonb),        -- выручка в ОПИУ из МойСклад
  ('auto_cogs', 'true'::jsonb),           -- себестоимость в ОПИУ из МойСклад
  ('debt_alert_days', '7'::jsonb),        -- за сколько дней предупреждать о сроке долга/платежа
  ('low_balance_limit', '0'::jsonb)       -- предупреждать, если остаток счёта ниже
on conflict (key) do nothing;

-- ── Стартовые статьи ─────────────────────────────────────────────────────
do $$
declare
  p bigint;
begin
  if exists (select 1 from public.fin_categories) then
    return;
  end if;

  insert into public.fin_categories (name, kind, opiu_group, sort) values ('Выручка от продаж', 'income', 'revenue', 10) returning id into p;
  insert into public.fin_categories (name, kind, opiu_group, sort) values ('Себестоимость проданного', 'expense', 'cogs', 20);

  insert into public.fin_categories (name, kind, opiu_group, sort) values ('Аренда и коммунальные', 'expense', 'opex', 30) returning id into p;
  insert into public.fin_categories (parent_id, name, kind, opiu_group, sort) values
    (p, 'Аренда', 'expense', 'opex', 1), (p, 'Коммунальные услуги', 'expense', 'opex', 2), (p, 'Интернет и связь', 'expense', 'opex', 3);

  insert into public.fin_categories (name, kind, opiu_group, sort) values ('Персонал', 'expense', 'opex', 40) returning id into p;
  insert into public.fin_categories (parent_id, name, kind, opiu_group, sort) values
    (p, 'Зарплата', 'expense', 'opex', 1), (p, 'Премии и бонусы', 'expense', 'opex', 2), (p, 'Налоги с зарплаты', 'expense', 'opex', 3);

  insert into public.fin_categories (name, kind, opiu_group, sort) values ('Маркетинг', 'expense', 'opex', 50) returning id into p;
  insert into public.fin_categories (parent_id, name, kind, opiu_group, sort) values
    (p, 'Таргетированная реклама', 'expense', 'opex', 1), (p, 'Блогеры и контент', 'expense', 'opex', 2), (p, 'Полиграфия и оформление', 'expense', 'opex', 3);

  insert into public.fin_categories (name, kind, opiu_group, sort) values ('Хозяйственные расходы', 'expense', 'opex', 60) returning id into p;
  insert into public.fin_categories (parent_id, name, kind, opiu_group, sort) values
    (p, 'Хозтовары и упаковка', 'expense', 'opex', 1), (p, 'Ремонт и обслуживание', 'expense', 'opex', 2), (p, 'Транспорт и доставка', 'expense', 'opex', 3);

  insert into public.fin_categories (name, kind, opiu_group, sort) values ('Банк и комиссии', 'expense', 'opex', 70);
  insert into public.fin_categories (name, kind, opiu_group, sort) values ('Налоги', 'expense', 'tax', 80);
  insert into public.fin_categories (name, kind, opiu_group, sort) values ('Прочие доходы', 'income', 'other_income', 90);
  insert into public.fin_categories (name, kind, opiu_group, sort) values ('Прочие расходы', 'expense', 'other_expense', 100);

  -- Движение капитала — в ОПИУ не входит
  insert into public.fin_categories (name, kind, opiu_group, sort) values ('Закупка товара поставщикам', 'expense', null, 110);
  insert into public.fin_categories (name, kind, opiu_group, sort) values ('Взнос партнёра / займ', 'income', null, 120);
  insert into public.fin_categories (name, kind, opiu_group, sort) values ('Выплата партнёру / возврат займа', 'expense', null, 130);
  insert into public.fin_categories (name, kind, opiu_group, sort) values ('Инвестиции в оборудование', 'expense', null, 140);
end $$;

-- ── RLS ──────────────────────────────────────────────────────────────────
-- Справочники (счета, статьи, партнёры, поставщики, настройки, план): читает
-- любой, кто видит хотя бы один финансовый раздел; пишет — finance.settings
-- (план ОПИУ — finance.opiu) с правом edit.
-- Операции, долги, платежи: по правам раздела и доступу к магазину
-- (операция без магазина — только тем, у кого доступ ко всем магазинам).

create or replace function public.has_finance_view()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.has_access('finance.overview', 'view')
      or public.has_access('finance.dds', 'view')
      or public.has_access('finance.opiu', 'view')
      or public.has_access('finance.debts', 'view')
      or public.has_access('finance.planned', 'view')
      or public.has_access('finance.settings', 'view');
$$;

create or replace function public.has_all_stores_access()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select not exists (
    select 1 from public.stores s where not public.has_store_access(s.code)
  );
$$;

do $$
declare
  t text;
begin
  foreach t in array array['fin_accounts', 'fin_categories', 'fin_partners', 'fin_suppliers', 'fin_settings'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists %I on public.%I', t || '_select', t);
    execute format('create policy %I on public.%I for select using (public.has_finance_view())', t || '_select', t);
    execute format('drop policy if exists %I on public.%I', t || '_write', t);
    execute format(
      'create policy %I on public.%I for all using (public.has_access(''finance.settings'', ''edit'')) with check (public.has_access(''finance.settings'', ''edit''))',
      t || '_write', t
    );
  end loop;
end $$;

-- План ОПИУ
alter table public.fin_pnl_plan enable row level security;
drop policy if exists fin_pnl_plan_select on public.fin_pnl_plan;
create policy fin_pnl_plan_select on public.fin_pnl_plan
  for select using (public.has_access('finance.opiu', 'view') and (store is null or public.has_store_access(store)));
drop policy if exists fin_pnl_plan_write on public.fin_pnl_plan;
create policy fin_pnl_plan_write on public.fin_pnl_plan
  for all using (public.has_access('finance.opiu', 'edit') and (store is null or public.has_store_access(store)))
  with check (public.has_access('finance.opiu', 'edit') and (store is null or public.has_store_access(store)));

-- Операции
alter table public.fin_operations enable row level security;
drop policy if exists fin_operations_select on public.fin_operations;
create policy fin_operations_select on public.fin_operations
  for select using (
    (public.has_access('finance.dds', 'view') or public.has_access('finance.overview', 'view')
      or public.has_access('finance.opiu', 'view') or public.has_access('finance.debts', 'view')
      or public.has_access('finance.planned', 'view'))
    and (store is null and public.has_all_stores_access() or store is not null and public.has_store_access(store))
  );
drop policy if exists fin_operations_write on public.fin_operations;
create policy fin_operations_write on public.fin_operations
  for all using (
    (public.has_access('finance.dds', 'edit') or public.has_access('finance.debts', 'edit') or public.has_access('finance.planned', 'edit'))
    and (store is null and public.has_all_stores_access() or store is not null and public.has_store_access(store))
  )
  with check (
    (public.has_access('finance.dds', 'edit') or public.has_access('finance.debts', 'edit') or public.has_access('finance.planned', 'edit'))
    and (store is null and public.has_all_stores_access() or store is not null and public.has_store_access(store))
  );

-- Долги
alter table public.fin_debts enable row level security;
drop policy if exists fin_debts_select on public.fin_debts;
create policy fin_debts_select on public.fin_debts
  for select using (
    (public.has_access('finance.debts', 'view') or public.has_access('finance.overview', 'view'))
    and public.has_store_access(store)
  );
drop policy if exists fin_debts_write on public.fin_debts;
create policy fin_debts_write on public.fin_debts
  for all using (public.has_access('finance.debts', 'edit') and public.has_store_access(store))
  with check (public.has_access('finance.debts', 'edit') and public.has_store_access(store));

alter table public.fin_debt_payments enable row level security;
drop policy if exists fin_debt_payments_select on public.fin_debt_payments;
create policy fin_debt_payments_select on public.fin_debt_payments
  for select using (
    exists (select 1 from public.fin_debts d where d.id = debt_id and public.has_store_access(d.store))
    and (public.has_access('finance.debts', 'view') or public.has_access('finance.overview', 'view'))
  );
drop policy if exists fin_debt_payments_write on public.fin_debt_payments;
create policy fin_debt_payments_write on public.fin_debt_payments
  for all using (
    public.has_access('finance.debts', 'edit')
    and exists (select 1 from public.fin_debts d where d.id = debt_id and public.has_store_access(d.store))
  )
  with check (
    public.has_access('finance.debts', 'edit')
    and exists (select 1 from public.fin_debts d where d.id = debt_id and public.has_store_access(d.store))
  );

-- Плановые платежи
alter table public.fin_planned_payments enable row level security;
drop policy if exists fin_planned_select on public.fin_planned_payments;
create policy fin_planned_select on public.fin_planned_payments
  for select using (
    (public.has_access('finance.planned', 'view') or public.has_access('finance.overview', 'view'))
    and (store is null and public.has_all_stores_access() or store is not null and public.has_store_access(store))
  );
drop policy if exists fin_planned_write on public.fin_planned_payments;
create policy fin_planned_write on public.fin_planned_payments
  for all using (
    public.has_access('finance.planned', 'edit')
    and (store is null and public.has_all_stores_access() or store is not null and public.has_store_access(store))
  )
  with check (
    public.has_access('finance.planned', 'edit')
    and (store is null and public.has_all_stores_access() or store is not null and public.has_store_access(store))
  );

-- Не даём удалить статью, на которую уже есть операции (restrict по fk есть
-- только на подпункты); архивировать — active = false.
alter table public.fin_operations drop constraint if exists fin_operations_debt_fk;
alter table public.fin_operations
  add constraint fin_operations_debt_fk foreign key (debt_id) references public.fin_debts(id) on delete set null;
