-- Подарочные сертификаты: ручной учёт через Telegram-бота (по кассе не пробиваются, в МойСклад
-- услуги нет). Продажа, использование (с привязкой к чеку МойСклад), возврат.
-- Пишет только сервер (service role — вебхук бота), страница портала пока не читает.

create table if not exists public.certificates (
  id bigint generated by default as identity primary key,
  store text not null references public.stores(code),
  number text not null,                           -- номер вручную, уникален во всей системе
  amount bigint not null check (amount > 0),      -- номинал, тенге
  pay_cash bigint not null default 0 check (pay_cash >= 0),     -- сколько оплачено наличными при продаже
  pay_noncash bigint not null default 0 check (pay_noncash >= 0), -- сколько безналом
  client_name text not null,
  client_phone text not null,
  seller_ms_id text not null,                     -- кто продал (запись остаётся на нём)
  seller_name text not null,
  created_by bigint references public.coach_users(id) on delete set null, -- кто внёс в бот
  sold_at timestamptz not null default now(),
  expires_at timestamptz not null,                -- срок действия 3 месяца
  status text not null default 'active'
    check (status in ('active', 'pending_use', 'used', 'returned')),

  -- привязка к чеку при использовании (pending_use — ждёт решения руководителя)
  use_demand_id text,
  use_demand_name text,
  use_demand_moment text,                         -- время чека в МойСклад как есть
  use_demand_sum bigint,                          -- тенге
  use_demand_cash bigint,
  use_demand_noncash bigint,
  use_demand_cashier text,
  use_requested_by bigint references public.coach_users(id) on delete set null,
  use_requested_at timestamptz,
  use_problem text,                               -- что не совпало, пока ждёт руководителя
  used_at timestamptz,

  returned_at timestamptz,
  returned_by text,

  -- по чеку, к которому привязан сертификат, был возврат в МойСклад (ночная проверка)
  demand_return_noticed_at timestamptz,
  demand_return_sum bigint not null default 0,
  demand_return_last_date date,
  demand_return_decision text check (demand_return_decision in ('kept', 'restored')),

  constraint certificates_pay_sum check (pay_cash + pay_noncash = amount)
);

create unique index if not exists certificates_number_unique on public.certificates (lower(btrim(number)));
create index if not exists certificates_store_status on public.certificates (store, status);
create index if not exists certificates_use_demand on public.certificates (use_demand_id) where use_demand_id is not null;

alter table public.certificates enable row level security;

-- Журнал действий: кто и что сделал с сертификатом.
create table if not exists public.certificate_events (
  id bigint generated by default as identity primary key,
  certificate_id bigint not null references public.certificates(id) on delete cascade,
  at timestamptz not null default now(),
  actor text not null,
  action text not null,
  note text
);
create index if not exists certificate_events_cert on public.certificate_events (certificate_id);
alter table public.certificate_events enable row level security;

-- Незаконченный диалог бота (продажа / выбор сертификата и чека): по одному на сотрудника.
create table if not exists public.certificate_drafts (
  coach_user_id bigint primary key references public.coach_users(id) on delete cascade,
  step text not null,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
alter table public.certificate_drafts enable row level security;
